### ISSUE TITLE
💡 [REQUEST] - Component based stories

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#10]
Start Date
No response

Implementation PR
No response

Reference Issues
No response

**Summary**
Description: This feature would allow users to pass custom Angular components as content for stories, providing more flexibility beyond the existing image and video options.
With this enhancement, users will be able to create stories that contain fully customizable content, such as forms, interactive elements, or any Angular component, rather than being limited to static media like photos or videos. The custom component will be rendered in place of the story media, taking up 100% of the story container’s height and width, ensuring seamless integration into the story UI.

**Key Changes:**
Story Interface Update: Modify the existing story interface to support not only image and video types but also custom components.
Flexible Content: Users can now pass a custom component to the story, which will be injected and displayed as the story content.
Full-Height Coverage: The custom component will occupy 100% of the story container’s height to ensure consistent and responsive design across all stories.

**Why?**
This enhancement will enable greater customization options, improving user experience by allowing them to personalize the appearance and behavior of story elements beyond just image/video

**Use Case:**
This feature is ideal for users who want to go beyond simple media stories and incorporate dynamic or interactive content (e.g., forms, polls, rich text, or animations) as part of their storytelling experience.

**Comment by Ashu1823** [comment]
Hi..
Intrested to work in this issue.
Can you please assign it to me?

**Comment by Gauravdarkslayer** [comment]
Hi @Ashu1823 ,
Is the is issue 100% clear to you?
Or do you need more clarifications before starting this?

**Comment by Ashu1823** [comment]
it will be better to get a clear ides about the work.. 
What I got is to create a common component to show the stories according to response.

**Comment by Gauravdarkslayer** [comment]
Alright, I'll be adding some more details on this issue, then we will connect for better clarifications. Sounds good?

**Comment by Ashu1823** [comment]
yes @Gauravdarkslayer sounds good

**Comment by Gauravdarkslayer** [comment]
Hi @Ashu1823 ,
I've updated the description and added some more details about the custom stories.
Let me know if it's clear to you, otherwise we can connect over discord to discuss more about it.

Discord username: `gauravdarkslayer`

**Comment by Gauravdarkslayer** [comment]
Hey @Ashu1823 ,
Any update on this issue ?

**Comment by Ashu1823** [comment]
hey @Gauravdarkslayer,
Due to healthg issues I am not able to pick anything..

**Comment by Gauravdarkslayer** [comment]
Oh it's okay!
Take Care !

**Comment by moudgalya1223** [comment]
hello @Gauravdarkslayer  created  a pr on this pls have look if this works else we will try naote r
