### ISSUE TITLE
[Request] - Improve current HomePage 

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#11]

**Comment by Sauhard74** [comment]
hey can i work on this issue?

**Comment by Gauravdarkslayer** [comment]
Sure @Sauhard74 ,
Can you share the figma design first before actually implementing it ?

**Comment by Sauhard74** [comment]
Yes sure

**Comment by Gauravdarkslayer** [comment]
Hey @Sauhard74 , Any update on this ?
Checkout this [figma](https://www.figma.com/design/Axlm1zGGLUYZtyCeUoOdEA/NGX-STORIES-(Angular)?node-id=0-1&node-type=canvas&t=UaHmT3AUQ82QHF3p-0) file, and let me know if it works well .

**Comment by Gauravdarkslayer** [comment]
@Sauhard74 , did you get any chance to checkout the figma file i've provided ?

**Comment by Sauhard74** [comment]
> @Sauhard74 , did you get any chance to checkout the figma file i've provided ?

Yup I saw that I will be soon pushing my pr

**Comment by Gauravdarkslayer** [comment]
Alright thanks !

**Comment by Gauravdarkslayer** [comment]
Hi @Sauhard74 ,
Any update on this issue ?

**Comment by Bharatdev1** [comment]
@Gauravdarkslayer , can you please assign this issue to me ?

**Comment by Gauravdarkslayer** [comment]
Sure, assigned
