### ISSUE TITLE
💡 [REQUEST] - Images should be placed from top if it's portrait and should come in middle if it's landscape.

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#16]
### Summary

Currently, the behavior for portrait and landscape images in the story container needs to be adjusted. For portrait-oriented images, the images should be aligned to the top of the container. 
For landscape-oriented images, they should be centered vertically within the container to maintain visual balance and proper user experience. This change would enhance the way stories are displayed, ensuring better visual adaptability for different image dimensions.

**Comment by SiddhanthKapoor** [comment]
I would like to work on this issue

**Comment by Ashu1823** [comment]
Hi..
Intrested to work in this issue.
Can you please assign it to me?

**Comment by Gauravdarkslayer** [comment]
@SiddhanthKapoor , Do you have any updates on this issue ?

**Comment by SiddhanthKapoor** [comment]
> @SiddhanthKapoor , Do you have any updates on this issue ?

yes , I'll be making a pull request within 2 days

**Comment by Gauravdarkslayer** [comment]
@SiddhanthKapoor I suggest you to check out this #54 PR, as i think this issue has been fixed here, you can try adjusting the height of story view. so that it appears in a single viewport without scrolling in desktop or mobile view.

**Comment by Gauravdarkslayer** [comment]
Done !
