### ISSUE TITLE
💡 [REQUEST] - Add left/right arrow buttons on desktop view only

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#17]
### Summary

Need to implement a new feature to improve the navigation experience on desktop devices. The goal is to add left and right arrow buttons for navigating through stories in desktop view. These buttons will allow users to move to the previous or next story using visible, clickable controls.

Details:

Arrow Buttons: Left and right arrow buttons should be visible only on desktop view. On mobile and tablet devices, the buttons should remain hidden.
Hiding/Disabling Taps: Currently, the user can navigate between stories by tapping on the left or right side of the screen. With the introduction of arrow buttons, the left/right taps for navigation should be disabled or hidden when the app is viewed on a desktop device. This ensures navigation is fully controlled by the newly added arrow buttons.

Acceptance Criteria:

Arrow buttons should only be visible on desktop view.
Left/right taps for story navigation should be disabled or hidden on desktop.
Mobile and tablet devices should continue using tap-based navigation without any changes.
This feature aims to provide a more user-friendly navigation experience for desktop users.

**Comment by Sauhard74** [comment]
hey can i work on this ?

**Comment by Piyush-Goenka** [comment]
Hey @Gauravdarkslayer ,
I’ll take on the task of implementing the new arrow button navigation feature for desktop devices. This will involve ensuring that the left and right arrow buttons are only visible on desktop views and disabling tap navigation on those devices to enhance user experience. I’ll also make sure that mobile and tablet navigation remains unchanged. Looking forward to improving our navigation for desktop users!
Please assign this issue to me.

**Comment by meetbhalodi11** [comment]
@Gauravdarkslayer Can you assign this to me? it's related to #19
