### ISSUE TITLE
💡 [REQUEST] - Center landscape images

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#22]
### Summary

When working with images in various layouts, especially on web pages, it is important to ensure that landscape-oriented images (i.e., images that are wider than they are tall) are displayed correctly. This issue focuses on centering such images horizontally and vertically within their container when their resolution is landscape.

Currently, landscape images may not be properly aligned, leading to inconsistent or visually unappealing layouts. The goal of this task is to detect if an image has a landscape resolution and, if so, automatically apply a CSS rule to center it within its container.

**Expected Behavior:**
Images with landscape resolution (width > height) should be horizontally centered within their container.
Portrait or square images should retain their current alignment (no changes needed for these).

**Example Scenario:**
Before:
A landscape image with a resolution of 1920x1080 is aligned to the top of its container, leaving empty space on the bottom side.
After:
The same landscape image is centered within its container, with equal space on both the left and right sides and top and bottom as well.

### Drawbacks

**Additional Considerations:**
Ensure the centering does not interfere with responsive layouts or mobile views.
Consider testing this behavior on different browsers and screen sizes to ensure consistent behavior.

**Comment by Piyush-Goenka** [comment]
Hey @Gauravdarkslayer 
I’ll take on this issue to ensure that landscape-oriented images are properly centered within their containers. I’ll focus on applying the necessary CSS rules to achieve this while keeping the current alignment for portrait and square images intact. Additionally, I’ll make sure to test across various browsers and screen sizes to maintain responsive behavior. Looking forward to enhancing our layout consistency!
Please assign this issue to me.

**Comment by Gauravdarkslayer** [comment]
Done in another commit.
