### ISSUE TITLE
💡 [REQUEST] - Display a loading indicator while images/videos within stories are being loaded

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#26]
### Summary

Currently, in the `ngx-stories` component, images within stories may take time to load, depending on network speed and file size. There is no visual feedback during this loading time, leading to a less smooth user experience. This feature request proposes adding a loading indicator that will be displayed while the image in a story is still loading, providing users with visual feedback until the content is fully rendered.

**Loading Indicator Display:**

Show a spinner or custom loading animation over the story until the image is fully loaded.
The loading indicator should automatically disappear once the image has finished loading.

**Responsiveness:**

Ensure the loading indicator works across different devices and screen sizes, including mobile and desktop.
This feature will enhance the user experience by providing feedback during the image loading process, making the interface feel more responsive and smooth.

**Additional Request**

While an image within a story is still loading, the story should not start playing, and the progress bar should remain paused. **The story's playback and the progress bar should only begin once the image has fully loaded**, ensuring that users do not miss any part of the story due to slow loading times. This will create a smoother and more user-friendly experience by preventing the story from advancing while the content is still being retrieved.

**Comment by Piyush-Goenka** [comment]
Hey @Gauravdarkslayer ,
I want to improve the ngx-stories component by adding a loading indicator for images, ensuring it displays while loading and disappears once the image is ready. Additionally, playback should pause until the image loads, enhancing the user experience by preventing users from missing any content.
Please assign this issue to me.

**Comment by Gauravdarkslayer** [comment]
Hi @Piyush-Goenka ,
Sure, assigned.

**Comment by Gauravdarkslayer** [comment]
Hi @Piyush-Goenka ,
Do you have any updates on this issue ?

**Comment by Piyush-Goenka** [comment]
I am unable to solve this 
Please assign this issue to someone else.

**Comment by Gauravdarkslayer** [comment]
Done in #70
