### ISSUE TITLE
💡 [REQUEST] - Add currentIndex feature for story navigation

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#27]
### Summary

Request to implement a currentIndex feature in the ngx-stories component, allowing users to control the current story being displayed. The feature should handle both scenarios:

**1. Multiple Story Groups:** Users can pass two properties, `currentGroupIndex` and `currentStoryIndex` , to navigate through stories within specific groups.
**2. Single Story Group:** Users can pass just a `currentStoryIndex` for simpler navigation when there is only one story group.

**- Default values for both the properties should be 0th index**

**- This addition should support flexible navigation across stories and groups, while maintaining backward compatibility for existing use cases.**

**Comment by Piyush-Goenka** [comment]
Hey @Gauravdarkslayer ,
I’ll take on the task of implementing the currentIndex feature in the ngx-stories component. This will allow users to control the displayed story more flexibly by passing currentGroupIndex and currentStoryIndex for multiple groups, or just currentStoryIndex for a single group. I’ll ensure that the default values are set to the 0th index and that this new feature maintains backward compatibility with existing use cases. Looking forward to enhancing the navigation experience!
Could you please assign this issue to me ?

**Comment by Gauravdarkslayer** [comment]
Alright @Piyush-Goenka ,
Let me know if you have any questions on this issue.
Thanks for picking this up.

**Comment by Gauravdarkslayer** [comment]
Hey @Piyush-Goenka ,
Any update on this issue ?

**Comment by Piyush-Goenka** [comment]
I am unable to solve this.
Please assign this issue to someone else.

**Comment by PRIME-SV** [comment]
As I can understand, Basically user will be able to start the story view at the specific story using two properties, currentGroupIndex and currentStoryIndex.
As mentioned in the request "support flexible navigation across stories and groups", I got the part where we can navigate through stories using button or other methods but do we have functionality to navigate through groups as well (skipping stories) ?.

**Comment by Gauravdarkslayer** [comment]
@PRIME-SV For both the questions, the answer is YES.
You can checkout the below functions in codebase.
`goToNextStoryGroup`
`goToPreviousStoryGroup`
Also add these properties(currentStoryIndex, currentStoryGroupIndex) in the `NgxStoriesOptions` itself.
As these properties gets initialized at component init so the functionality should work without manually triggering any other function.
So you can try and test on your end also Please do let me know in case you have any questions.

**Comment by Gauravdarkslayer** [comment]
Done
